.Dd March 07, 2024
.Dt 3SG 1
.Os
.Sh NAME
.Nm 3sg
.Nd suckless static site generator
.Sh SYNOPSIS
.Nm
.Op Fl c Ar config
.Op Fl o Ar output_dir
.Op Fl p Ar project_dir
.Op Fl w Ar web_root
.Sh DESCRIPTION
A minimal, unrestrictive static site generator (SSG) written in ??? lines of C,
inspired by saait.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c Ar config
Specify the global configuration file, whose variables can be overridden by
page-specific .cfg files (default "global.cfg").
.It Fl o Ar output_dir
Specify the output directory for the generated site (default "output").
.It Fl p Ar project_dir
Specify the project base directory from which
.Nm
operates (default "."). This is relevant for TEMPLATE and [INCL ...].
.It Fl w Ar web_root
Specify the web root directory for [PATH] (default "content").
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr saait 1
.Sh AUTHORS
.An Andy Sukowski\-Bang Aq Mt andy@3sg.dev
